# Generated by Django 4.0.3 on 2022-03-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigOperatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('id_operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurazioni_operatore', to='Appuntamenti.operatore')),
                ('id_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_num', to='Appuntamenti.configslot')),
            ],
        ),
    ]
