# Generated by Django 4.0.3 on 2022-03-22 13:58

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Appuntamenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('status', model_utils.fields.StatusField(choices=[('attivo', 'attivo'), ('non attivo', 'non attivo'), ('occupato', 'occupato')], default='attivo', max_length=100, no_check_for_status=True)),
            ],
        ),
        migrations.RenameField(
            model_name='configslot',
            old_name='valore',
            new_name='slot_time_value',
        ),
        migrations.RemoveField(
            model_name='configoperatore',
            name='id_operatore',
        ),
        migrations.DeleteModel(
            name='Operatore',
        ),
        migrations.AddField(
            model_name='configoperatore',
            name='id_operator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operator_config', to='Appuntamenti.operator'),
            preserve_default=False,
        ),
    ]
