# Generated by Django 4.0.3 on 2022-03-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuntamenti', '0002_operator_rename_valore_configslot_slot_time_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operator', 'verbose_name_plural': 'Operators'},
        ),
        migrations.AlterField(
            model_name='configoperatore',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='configoperatore',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
