# Generated by Django 4.0.3 on 2022-03-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appuntamenti', '0003_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigOperatore',
            new_name='ConfigOperator',
        ),
    ]
